# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --livereload-port 35729"

volumes:
  bundle_cache:
